root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--config", "./config.local.yml"]
  bin = "./tmp/pxgrider"
  cmd = """go build --trimpath -ldflags "\
    -X github.com/vkumov/go-pxgrider/server/internal/config.BuildStamp=`date -u '+%Y-%m-%d_%I:%M:%S%p'` \
    -X github.com/vkumov/go-pxgrider/server/internal/config.GitHash=`git rev-parse HEAD` \
    -X github.com/vkumov/go-pxgrider/server/internal/config.V=`git describe --always --tags --dirty`\
  " -buildvcs=false -o ./tmp/pxgrider ./server/bin/*.go"""
  delay = 0
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true