// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: proto/connection_logs.proto

package pxgrider_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Client    string                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Level     string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message   string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Label     string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *ConnectionLog) Reset() {
	*x = ConnectionLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionLog) ProtoMessage() {}

func (x *ConnectionLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionLog.ProtoReflect.Descriptor instead.
func (*ConnectionLog) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectionLog) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ConnectionLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ConnectionLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConnectionLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionLog) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetConnectionLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Limit        int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int64  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetConnectionLogsRequest) Reset() {
	*x = GetConnectionLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionLogsRequest) ProtoMessage() {}

func (x *GetConnectionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionLogsRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectionLogsRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetConnectionLogsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetConnectionLogsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConnectionLogsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetConnectionLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionLogs []*ConnectionLog `protobuf:"bytes,1,rep,name=connection_logs,json=connectionLogs,proto3" json:"connection_logs,omitempty"`
	Total          int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit          int64            `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int64            `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetConnectionLogsResponse) Reset() {
	*x = GetConnectionLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionLogsResponse) ProtoMessage() {}

func (x *GetConnectionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionLogsResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionLogsResponse) GetConnectionLogs() []*ConnectionLog {
	if x != nil {
		return x.ConnectionLogs
	}
	return nil
}

func (x *GetConnectionLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetConnectionLogsResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConnectionLogsResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LogIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *LogIDs) Reset() {
	*x = LogIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogIDs) ProtoMessage() {}

func (x *LogIDs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogIDs.ProtoReflect.Descriptor instead.
func (*LogIDs) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{3}
}

func (x *LogIDs) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteConnectionLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Types that are assignable to What:
	//
	//	*DeleteConnectionLogsRequest_LogIds
	//	*DeleteConnectionLogsRequest_All
	What isDeleteConnectionLogsRequest_What `protobuf_oneof:"what"`
}

func (x *DeleteConnectionLogsRequest) Reset() {
	*x = DeleteConnectionLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConnectionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionLogsRequest) ProtoMessage() {}

func (x *DeleteConnectionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionLogsRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectionLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteConnectionLogsRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteConnectionLogsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (m *DeleteConnectionLogsRequest) GetWhat() isDeleteConnectionLogsRequest_What {
	if m != nil {
		return m.What
	}
	return nil
}

func (x *DeleteConnectionLogsRequest) GetLogIds() *LogIDs {
	if x, ok := x.GetWhat().(*DeleteConnectionLogsRequest_LogIds); ok {
		return x.LogIds
	}
	return nil
}

func (x *DeleteConnectionLogsRequest) GetAll() bool {
	if x, ok := x.GetWhat().(*DeleteConnectionLogsRequest_All); ok {
		return x.All
	}
	return false
}

type isDeleteConnectionLogsRequest_What interface {
	isDeleteConnectionLogsRequest_What()
}

type DeleteConnectionLogsRequest_LogIds struct {
	LogIds *LogIDs `protobuf:"bytes,3,opt,name=log_ids,json=logIds,proto3,oneof"`
}

type DeleteConnectionLogsRequest_All struct {
	All bool `protobuf:"varint,4,opt,name=all,proto3,oneof"`
}

func (*DeleteConnectionLogsRequest_LogIds) isDeleteConnectionLogsRequest_What() {}

func (*DeleteConnectionLogsRequest_All) isDeleteConnectionLogsRequest_What() {}

type DeleteConnectionLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted int64 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteConnectionLogsResponse) Reset() {
	*x = DeleteConnectionLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_logs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConnectionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionLogsResponse) ProtoMessage() {}

func (x *DeleteConnectionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_logs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionLogsResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectionLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_logs_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteConnectionLogsResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_proto_connection_logs_proto protoreflect.FileDescriptor

var file_proto_connection_logs_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70,
	0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x97, 0x01, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x78,
	0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x1a,
	0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x49, 0x44, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x1b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x6c, 0x6f, 0x67,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x78, 0x67,
	0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x49,
	0x44, 0x73, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x03,
	0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c,
	0x42, 0x06, 0x0a, 0x04, 0x77, 0x68, 0x61, 0x74, 0x22, 0x38, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x42, 0x38, 0x5a, 0x36, 0x77, 0x77, 0x77, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6b, 0x75, 0x6d, 0x6f,
	0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x78,
	0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_connection_logs_proto_rawDescOnce sync.Once
	file_proto_connection_logs_proto_rawDescData = file_proto_connection_logs_proto_rawDesc
)

func file_proto_connection_logs_proto_rawDescGZIP() []byte {
	file_proto_connection_logs_proto_rawDescOnce.Do(func() {
		file_proto_connection_logs_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_connection_logs_proto_rawDescData)
	})
	return file_proto_connection_logs_proto_rawDescData
}

var file_proto_connection_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_connection_logs_proto_goTypes = []interface{}{
	(*ConnectionLog)(nil),                // 0: pxgrider_proto.ConnectionLog
	(*GetConnectionLogsRequest)(nil),     // 1: pxgrider_proto.GetConnectionLogsRequest
	(*GetConnectionLogsResponse)(nil),    // 2: pxgrider_proto.GetConnectionLogsResponse
	(*LogIDs)(nil),                       // 3: pxgrider_proto.LogIDs
	(*DeleteConnectionLogsRequest)(nil),  // 4: pxgrider_proto.DeleteConnectionLogsRequest
	(*DeleteConnectionLogsResponse)(nil), // 5: pxgrider_proto.DeleteConnectionLogsResponse
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
	(*User)(nil),                         // 7: pxgrider_proto.User
}
var file_proto_connection_logs_proto_depIdxs = []int32{
	6, // 0: pxgrider_proto.ConnectionLog.timestamp:type_name -> google.protobuf.Timestamp
	7, // 1: pxgrider_proto.GetConnectionLogsRequest.user:type_name -> pxgrider_proto.User
	0, // 2: pxgrider_proto.GetConnectionLogsResponse.connection_logs:type_name -> pxgrider_proto.ConnectionLog
	7, // 3: pxgrider_proto.DeleteConnectionLogsRequest.user:type_name -> pxgrider_proto.User
	3, // 4: pxgrider_proto.DeleteConnectionLogsRequest.log_ids:type_name -> pxgrider_proto.LogIDs
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_connection_logs_proto_init() }
func file_proto_connection_logs_proto_init() {
	if File_proto_connection_logs_proto != nil {
		return
	}
	file_proto_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_connection_logs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_logs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_logs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_logs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_logs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConnectionLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_logs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConnectionLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_connection_logs_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*DeleteConnectionLogsRequest_LogIds)(nil),
		(*DeleteConnectionLogsRequest_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_connection_logs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_connection_logs_proto_goTypes,
		DependencyIndexes: file_proto_connection_logs_proto_depIdxs,
		MessageInfos:      file_proto_connection_logs_proto_msgTypes,
	}.Build()
	File_proto_connection_logs_proto = out.File
	file_proto_connection_logs_proto_rawDesc = nil
	file_proto_connection_logs_proto_goTypes = nil
	file_proto_connection_logs_proto_depIdxs = nil
}
