// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: proto/connection_messages.proto

package pxgrider_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Client    string                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Topic     string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Viewed    bool                   `protobuf:"varint,6,opt,name=viewed,proto3" json:"viewed,omitempty"`
}

func (x *ConnectionMessage) Reset() {
	*x = ConnectionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMessage) ProtoMessage() {}

func (x *ConnectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMessage.ProtoReflect.Descriptor instead.
func (*ConnectionMessage) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectionMessage) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ConnectionMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConnectionMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConnectionMessage) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

type GetConnectionMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Limit        int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int64  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetConnectionMessagesRequest) Reset() {
	*x = GetConnectionMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionMessagesRequest) ProtoMessage() {}

func (x *GetConnectionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectionMessagesRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetConnectionMessagesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetConnectionMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConnectionMessagesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetConnectionMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*ConnectionMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total    int64                `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit    int64                `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset   int64                `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetConnectionMessagesResponse) Reset() {
	*x = GetConnectionMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionMessagesResponse) ProtoMessage() {}

func (x *GetConnectionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionMessagesResponse) GetMessages() []*ConnectionMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetConnectionMessagesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetConnectionMessagesResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetConnectionMessagesResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MarkConnectionMessagesAsReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ConnectionId string  `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	MessageIds   []int64 `protobuf:"varint,3,rep,packed,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
}

func (x *MarkConnectionMessagesAsReadRequest) Reset() {
	*x = MarkConnectionMessagesAsReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkConnectionMessagesAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConnectionMessagesAsReadRequest) ProtoMessage() {}

func (x *MarkConnectionMessagesAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConnectionMessagesAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkConnectionMessagesAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MarkConnectionMessagesAsReadRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MarkConnectionMessagesAsReadRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *MarkConnectionMessagesAsReadRequest) GetMessageIds() []int64 {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type MarkConnectionMessagesAsReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarkConnectionMessagesAsReadResponse) Reset() {
	*x = MarkConnectionMessagesAsReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkConnectionMessagesAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConnectionMessagesAsReadResponse) ProtoMessage() {}

func (x *MarkConnectionMessagesAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConnectionMessagesAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkConnectionMessagesAsReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{4}
}

type MessageIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *MessageIDs) Reset() {
	*x = MessageIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIDs) ProtoMessage() {}

func (x *MessageIDs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIDs.ProtoReflect.Descriptor instead.
func (*MessageIDs) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessageIDs) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteConnectionMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Types that are assignable to What:
	//
	//	*DeleteConnectionMessagesRequest_MessageIds
	//	*DeleteConnectionMessagesRequest_All
	What isDeleteConnectionMessagesRequest_What `protobuf_oneof:"what"`
}

func (x *DeleteConnectionMessagesRequest) Reset() {
	*x = DeleteConnectionMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConnectionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionMessagesRequest) ProtoMessage() {}

func (x *DeleteConnectionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionMessagesRequest.ProtoReflect.Descriptor instead.
func (*DeleteConnectionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConnectionMessagesRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteConnectionMessagesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (m *DeleteConnectionMessagesRequest) GetWhat() isDeleteConnectionMessagesRequest_What {
	if m != nil {
		return m.What
	}
	return nil
}

func (x *DeleteConnectionMessagesRequest) GetMessageIds() *MessageIDs {
	if x, ok := x.GetWhat().(*DeleteConnectionMessagesRequest_MessageIds); ok {
		return x.MessageIds
	}
	return nil
}

func (x *DeleteConnectionMessagesRequest) GetAll() bool {
	if x, ok := x.GetWhat().(*DeleteConnectionMessagesRequest_All); ok {
		return x.All
	}
	return false
}

type isDeleteConnectionMessagesRequest_What interface {
	isDeleteConnectionMessagesRequest_What()
}

type DeleteConnectionMessagesRequest_MessageIds struct {
	MessageIds *MessageIDs `protobuf:"bytes,3,opt,name=message_ids,json=messageIds,proto3,oneof"`
}

type DeleteConnectionMessagesRequest_All struct {
	All bool `protobuf:"varint,4,opt,name=all,proto3,oneof"`
}

func (*DeleteConnectionMessagesRequest_MessageIds) isDeleteConnectionMessagesRequest_What() {}

func (*DeleteConnectionMessagesRequest_All) isDeleteConnectionMessagesRequest_What() {}

type DeleteConnectionMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted int64 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteConnectionMessagesResponse) Reset() {
	*x = DeleteConnectionMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connection_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConnectionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnectionMessagesResponse) ProtoMessage() {}

func (x *DeleteConnectionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnectionMessagesResponse.ProtoReflect.Descriptor instead.
func (*DeleteConnectionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConnectionMessagesResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_proto_connection_messages_proto protoreflect.FileDescriptor

var file_proto_connection_messages_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x69, 0x65, 0x77, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x76, 0x69,
	0x65, 0x77, 0x65, 0x64, 0x22, 0x9b, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x23, 0x4d, 0x61, 0x72, 0x6b,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x22,
	0x26, 0x0a, 0x24, 0x4d, 0x61, 0x72, 0x6b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x41, 0x73, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x44, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x1f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x78, 0x67, 0x72,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x61, 0x6c, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x42, 0x06, 0x0a,
	0x04, 0x77, 0x68, 0x61, 0x74, 0x22, 0x3c, 0x0a, 0x20, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x42, 0x38, 0x5a, 0x36, 0x77, 0x77, 0x77, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6b, 0x75, 0x6d,
	0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x70,
	0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_connection_messages_proto_rawDescOnce sync.Once
	file_proto_connection_messages_proto_rawDescData = file_proto_connection_messages_proto_rawDesc
)

func file_proto_connection_messages_proto_rawDescGZIP() []byte {
	file_proto_connection_messages_proto_rawDescOnce.Do(func() {
		file_proto_connection_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_connection_messages_proto_rawDescData)
	})
	return file_proto_connection_messages_proto_rawDescData
}

var file_proto_connection_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_connection_messages_proto_goTypes = []interface{}{
	(*ConnectionMessage)(nil),                    // 0: pxgrider_proto.ConnectionMessage
	(*GetConnectionMessagesRequest)(nil),         // 1: pxgrider_proto.GetConnectionMessagesRequest
	(*GetConnectionMessagesResponse)(nil),        // 2: pxgrider_proto.GetConnectionMessagesResponse
	(*MarkConnectionMessagesAsReadRequest)(nil),  // 3: pxgrider_proto.MarkConnectionMessagesAsReadRequest
	(*MarkConnectionMessagesAsReadResponse)(nil), // 4: pxgrider_proto.MarkConnectionMessagesAsReadResponse
	(*MessageIDs)(nil),                           // 5: pxgrider_proto.MessageIDs
	(*DeleteConnectionMessagesRequest)(nil),      // 6: pxgrider_proto.DeleteConnectionMessagesRequest
	(*DeleteConnectionMessagesResponse)(nil),     // 7: pxgrider_proto.DeleteConnectionMessagesResponse
	(*timestamppb.Timestamp)(nil),                // 8: google.protobuf.Timestamp
	(*User)(nil),                                 // 9: pxgrider_proto.User
}
var file_proto_connection_messages_proto_depIdxs = []int32{
	8, // 0: pxgrider_proto.ConnectionMessage.timestamp:type_name -> google.protobuf.Timestamp
	9, // 1: pxgrider_proto.GetConnectionMessagesRequest.user:type_name -> pxgrider_proto.User
	0, // 2: pxgrider_proto.GetConnectionMessagesResponse.messages:type_name -> pxgrider_proto.ConnectionMessage
	9, // 3: pxgrider_proto.MarkConnectionMessagesAsReadRequest.user:type_name -> pxgrider_proto.User
	9, // 4: pxgrider_proto.DeleteConnectionMessagesRequest.user:type_name -> pxgrider_proto.User
	5, // 5: pxgrider_proto.DeleteConnectionMessagesRequest.message_ids:type_name -> pxgrider_proto.MessageIDs
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_connection_messages_proto_init() }
func file_proto_connection_messages_proto_init() {
	if File_proto_connection_messages_proto != nil {
		return
	}
	file_proto_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_connection_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkConnectionMessagesAsReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkConnectionMessagesAsReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConnectionMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connection_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConnectionMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_connection_messages_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*DeleteConnectionMessagesRequest_MessageIds)(nil),
		(*DeleteConnectionMessagesRequest_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_connection_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_connection_messages_proto_goTypes,
		DependencyIndexes: file_proto_connection_messages_proto_depIdxs,
		MessageInfos:      file_proto_connection_messages_proto_msgTypes,
	}.Build()
	File_proto_connection_messages_proto = out.File
	file_proto_connection_messages_proto_rawDesc = nil
	file_proto_connection_messages_proto_goTypes = nil
	file_proto_connection_messages_proto_depIdxs = nil
}
