// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: proto/credentials.proto

package pxgrider_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsType int32

const (
	CredentialsType_CREDENTIALS_TYPE_UNSPECIFIED CredentialsType = 0
	CredentialsType_CREDENTIALS_TYPE_PASSWORD    CredentialsType = 1
	CredentialsType_CREDENTIALS_TYPE_CERTIFICATE CredentialsType = 2
)

// Enum value maps for CredentialsType.
var (
	CredentialsType_name = map[int32]string{
		0: "CREDENTIALS_TYPE_UNSPECIFIED",
		1: "CREDENTIALS_TYPE_PASSWORD",
		2: "CREDENTIALS_TYPE_CERTIFICATE",
	}
	CredentialsType_value = map[string]int32{
		"CREDENTIALS_TYPE_UNSPECIFIED": 0,
		"CREDENTIALS_TYPE_PASSWORD":    1,
		"CREDENTIALS_TYPE_CERTIFICATE": 2,
	}
)

func (x CredentialsType) Enum() *CredentialsType {
	p := new(CredentialsType)
	*p = x
	return p
}

func (x CredentialsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CredentialsType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_credentials_proto_enumTypes[0].Descriptor()
}

func (CredentialsType) Type() protoreflect.EnumType {
	return &file_proto_credentials_proto_enumTypes[0]
}

func (x CredentialsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CredentialsType.Descriptor instead.
func (CredentialsType) EnumDescriptor() ([]byte, []int) {
	return file_proto_credentials_proto_rawDescGZIP(), []int{0}
}

type CredentialsPassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CredentialsPassword) Reset() {
	*x = CredentialsPassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_credentials_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialsPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsPassword) ProtoMessage() {}

func (x *CredentialsPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credentials_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsPassword.ProtoReflect.Descriptor instead.
func (*CredentialsPassword) Descriptor() ([]byte, []int) {
	return file_proto_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsPassword) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CredentialsCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey     string   `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Certificate    string   `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	CaCertificates []string `protobuf:"bytes,3,rep,name=ca_certificates,json=caCertificates,proto3" json:"ca_certificates,omitempty"`
}

func (x *CredentialsCertificate) Reset() {
	*x = CredentialsCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_credentials_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CredentialsCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsCertificate) ProtoMessage() {}

func (x *CredentialsCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credentials_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsCertificate.ProtoReflect.Descriptor instead.
func (*CredentialsCertificate) Descriptor() ([]byte, []int) {
	return file_proto_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialsCertificate) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CredentialsCertificate) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *CredentialsCertificate) GetCaCertificates() []string {
	if x != nil {
		return x.CaCertificates
	}
	return nil
}

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     CredentialsType `protobuf:"varint,1,opt,name=type,proto3,enum=pxgrider_proto.CredentialsType" json:"type,omitempty"`
	NodeName string          `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Types that are assignable to Kind:
	//
	//	*Credentials_Password
	//	*Credentials_Certificate
	Kind isCredentials_Kind `protobuf_oneof:"kind"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_credentials_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credentials_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_proto_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *Credentials) GetType() CredentialsType {
	if x != nil {
		return x.Type
	}
	return CredentialsType_CREDENTIALS_TYPE_UNSPECIFIED
}

func (x *Credentials) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (m *Credentials) GetKind() isCredentials_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Credentials) GetPassword() *CredentialsPassword {
	if x, ok := x.GetKind().(*Credentials_Password); ok {
		return x.Password
	}
	return nil
}

func (x *Credentials) GetCertificate() *CredentialsCertificate {
	if x, ok := x.GetKind().(*Credentials_Certificate); ok {
		return x.Certificate
	}
	return nil
}

type isCredentials_Kind interface {
	isCredentials_Kind()
}

type Credentials_Password struct {
	Password *CredentialsPassword `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type Credentials_Certificate struct {
	Certificate *CredentialsCertificate `protobuf:"bytes,4,opt,name=certificate,proto3,oneof"`
}

func (*Credentials_Password) isCredentials_Kind() {}

func (*Credentials_Certificate) isCredentials_Kind() {}

var File_proto_credentials_proto protoreflect.FileDescriptor

var file_proto_credentials_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x78, 0x67, 0x72, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x84, 0x01, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61,
	0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x73, 0x22, 0xf6, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x4a, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x2a, 0x74, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x1c, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01,
	0x12, 0x20, 0x0a, 0x1c, 0x43, 0x52, 0x45, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x53, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x42, 0x38, 0x5a, 0x36, 0x77, 0x77, 0x77, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6b, 0x75, 0x6d, 0x6f,
	0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x78,
	0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_credentials_proto_rawDescOnce sync.Once
	file_proto_credentials_proto_rawDescData = file_proto_credentials_proto_rawDesc
)

func file_proto_credentials_proto_rawDescGZIP() []byte {
	file_proto_credentials_proto_rawDescOnce.Do(func() {
		file_proto_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_credentials_proto_rawDescData)
	})
	return file_proto_credentials_proto_rawDescData
}

var file_proto_credentials_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_credentials_proto_goTypes = []interface{}{
	(CredentialsType)(0),           // 0: pxgrider_proto.CredentialsType
	(*CredentialsPassword)(nil),    // 1: pxgrider_proto.CredentialsPassword
	(*CredentialsCertificate)(nil), // 2: pxgrider_proto.CredentialsCertificate
	(*Credentials)(nil),            // 3: pxgrider_proto.Credentials
}
var file_proto_credentials_proto_depIdxs = []int32{
	0, // 0: pxgrider_proto.Credentials.type:type_name -> pxgrider_proto.CredentialsType
	1, // 1: pxgrider_proto.Credentials.password:type_name -> pxgrider_proto.CredentialsPassword
	2, // 2: pxgrider_proto.Credentials.certificate:type_name -> pxgrider_proto.CredentialsCertificate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_credentials_proto_init() }
func file_proto_credentials_proto_init() {
	if File_proto_credentials_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_credentials_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialsPassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_credentials_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CredentialsCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_credentials_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_credentials_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Credentials_Password)(nil),
		(*Credentials_Certificate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_credentials_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_credentials_proto_goTypes,
		DependencyIndexes: file_proto_credentials_proto_depIdxs,
		EnumInfos:         file_proto_credentials_proto_enumTypes,
		MessageInfos:      file_proto_credentials_proto_msgTypes,
	}.Build()
	File_proto_credentials_proto = out.File
	file_proto_credentials_proto_rawDesc = nil
	file_proto_credentials_proto_goTypes = nil
	file_proto_credentials_proto_depIdxs = nil
}
