// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.1
// source: proto/fqdn.proto

package pxgrider_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyPreference int32

const (
	FamilyPreference_FamilyPreference_IPv4        FamilyPreference = 0
	FamilyPreference_FamilyPreference_IPv6        FamilyPreference = 1
	FamilyPreference_FamilyPreference_IPv4AndIPv6 FamilyPreference = 2
	FamilyPreference_FamilyPreference_IPv6AndIPv4 FamilyPreference = 3
)

// Enum value maps for FamilyPreference.
var (
	FamilyPreference_name = map[int32]string{
		0: "FamilyPreference_IPv4",
		1: "FamilyPreference_IPv6",
		2: "FamilyPreference_IPv4AndIPv6",
		3: "FamilyPreference_IPv6AndIPv4",
	}
	FamilyPreference_value = map[string]int32{
		"FamilyPreference_IPv4":        0,
		"FamilyPreference_IPv6":        1,
		"FamilyPreference_IPv4AndIPv6": 2,
		"FamilyPreference_IPv6AndIPv4": 3,
	}
)

func (x FamilyPreference) Enum() *FamilyPreference {
	p := new(FamilyPreference)
	*p = x
	return p
}

func (x FamilyPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FamilyPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fqdn_proto_enumTypes[0].Descriptor()
}

func (FamilyPreference) Type() protoreflect.EnumType {
	return &file_proto_fqdn_proto_enumTypes[0]
}

func (x FamilyPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FamilyPreference.Descriptor instead.
func (FamilyPreference) EnumDescriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{0}
}

type Family int32

const (
	Family_INET_IPv4 Family = 0
	Family_INET_IPv6 Family = 1
)

// Enum value maps for Family.
var (
	Family_name = map[int32]string{
		0: "INET_IPv4",
		1: "INET_IPv6",
	}
	Family_value = map[string]int32{
		"INET_IPv4": 0,
		"INET_IPv6": 1,
	}
)

func (x Family) Enum() *Family {
	p := new(Family)
	*p = x
	return p
}

func (x Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Family) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fqdn_proto_enumTypes[1].Descriptor()
}

func (Family) Type() protoreflect.EnumType {
	return &file_proto_fqdn_proto_enumTypes[1]
}

func (x Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Family.Descriptor instead.
func (Family) EnumDescriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{1}
}

type DNS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DNS) Reset() {
	*x = DNS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fqdn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNS) ProtoMessage() {}

func (x *DNS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fqdn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNS.ProtoReflect.Descriptor instead.
func (*DNS) Descriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{0}
}

func (x *DNS) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DNS) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CheckFQDNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fqdn             string           `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Dns              *DNS             `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	FamilyPreference FamilyPreference `protobuf:"varint,3,opt,name=family_preference,json=familyPreference,proto3,enum=pxgrider_proto.FamilyPreference" json:"family_preference,omitempty"`
}

func (x *CheckFQDNRequest) Reset() {
	*x = CheckFQDNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fqdn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFQDNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFQDNRequest) ProtoMessage() {}

func (x *CheckFQDNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fqdn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFQDNRequest.ProtoReflect.Descriptor instead.
func (*CheckFQDNRequest) Descriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{1}
}

func (x *CheckFQDNRequest) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *CheckFQDNRequest) GetDns() *DNS {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *CheckFQDNRequest) GetFamilyPreference() FamilyPreference {
	if x != nil {
		return x.FamilyPreference
	}
	return FamilyPreference_FamilyPreference_IPv4
}

type IP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Family Family `protobuf:"varint,2,opt,name=family,proto3,enum=pxgrider_proto.Family" json:"family,omitempty"`
}

func (x *IP) Reset() {
	*x = IP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fqdn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fqdn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{2}
}

func (x *IP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IP) GetFamily() Family {
	if x != nil {
		return x.Family
	}
	return Family_INET_IPv4
}

type CheckFQDNResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid   bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Candidate *IP    `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Ips       []*IP  `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CheckFQDNResponse) Reset() {
	*x = CheckFQDNResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_fqdn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFQDNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFQDNResponse) ProtoMessage() {}

func (x *CheckFQDNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fqdn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFQDNResponse.ProtoReflect.Descriptor instead.
func (*CheckFQDNResponse) Descriptor() ([]byte, []int) {
	return file_proto_fqdn_proto_rawDescGZIP(), []int{3}
}

func (x *CheckFQDNResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *CheckFQDNResponse) GetCandidate() *IP {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *CheckFQDNResponse) GetIps() []*IP {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *CheckFQDNResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_fqdn_proto protoreflect.FileDescriptor

var file_proto_fqdn_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x71, 0x64, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x29, 0x0a, 0x03, 0x44, 0x4e, 0x53, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x9c, 0x01,
	0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x51, 0x44, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x71, 0x64, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x71, 0x64, 0x6e, 0x12, 0x25, 0x0a, 0x03, 0x64, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x4e, 0x53, 0x52, 0x03, 0x64, 0x6e, 0x73, 0x12, 0x4d, 0x0a,
	0x11, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69,
	0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x10, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x44, 0x0a, 0x02,
	0x49, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x2e, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x51, 0x44, 0x4e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x50, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x50, 0x52, 0x03, 0x69, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x8c, 0x01, 0x0a, 0x10, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x49, 0x50, 0x76, 0x34, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x49, 0x50, 0x76, 0x36, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x49, 0x50, 0x76, 0x34, 0x41, 0x6e, 0x64, 0x49, 0x50, 0x76, 0x36, 0x10, 0x02, 0x12, 0x20,
	0x0a, 0x1c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x5f, 0x49, 0x50, 0x76, 0x36, 0x41, 0x6e, 0x64, 0x49, 0x50, 0x76, 0x34, 0x10, 0x03,
	0x2a, 0x26, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e,
	0x45, 0x54, 0x5f, 0x49, 0x50, 0x76, 0x34, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x45,
	0x54, 0x5f, 0x49, 0x50, 0x76, 0x36, 0x10, 0x01, 0x42, 0x38, 0x5a, 0x36, 0x77, 0x77, 0x77, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x76, 0x6b, 0x75, 0x6d, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x78, 0x67, 0x72, 0x69,
	0x64, 0x65, 0x72, 0x2f, 0x70, 0x78, 0x67, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_fqdn_proto_rawDescOnce sync.Once
	file_proto_fqdn_proto_rawDescData = file_proto_fqdn_proto_rawDesc
)

func file_proto_fqdn_proto_rawDescGZIP() []byte {
	file_proto_fqdn_proto_rawDescOnce.Do(func() {
		file_proto_fqdn_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_fqdn_proto_rawDescData)
	})
	return file_proto_fqdn_proto_rawDescData
}

var file_proto_fqdn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_fqdn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_fqdn_proto_goTypes = []interface{}{
	(FamilyPreference)(0),     // 0: pxgrider_proto.FamilyPreference
	(Family)(0),               // 1: pxgrider_proto.Family
	(*DNS)(nil),               // 2: pxgrider_proto.DNS
	(*CheckFQDNRequest)(nil),  // 3: pxgrider_proto.CheckFQDNRequest
	(*IP)(nil),                // 4: pxgrider_proto.IP
	(*CheckFQDNResponse)(nil), // 5: pxgrider_proto.CheckFQDNResponse
}
var file_proto_fqdn_proto_depIdxs = []int32{
	2, // 0: pxgrider_proto.CheckFQDNRequest.dns:type_name -> pxgrider_proto.DNS
	0, // 1: pxgrider_proto.CheckFQDNRequest.family_preference:type_name -> pxgrider_proto.FamilyPreference
	1, // 2: pxgrider_proto.IP.family:type_name -> pxgrider_proto.Family
	4, // 3: pxgrider_proto.CheckFQDNResponse.candidate:type_name -> pxgrider_proto.IP
	4, // 4: pxgrider_proto.CheckFQDNResponse.ips:type_name -> pxgrider_proto.IP
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_fqdn_proto_init() }
func file_proto_fqdn_proto_init() {
	if File_proto_fqdn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_fqdn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fqdn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFQDNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fqdn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_fqdn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFQDNResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_fqdn_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_fqdn_proto_goTypes,
		DependencyIndexes: file_proto_fqdn_proto_depIdxs,
		EnumInfos:         file_proto_fqdn_proto_enumTypes,
		MessageInfos:      file_proto_fqdn_proto_msgTypes,
	}.Build()
	File_proto_fqdn_proto = out.File
	file_proto_fqdn_proto_rawDesc = nil
	file_proto_fqdn_proto_goTypes = nil
	file_proto_fqdn_proto_depIdxs = nil
}
